@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jellyfishing.core.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;