@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jellyfishing.core.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;