@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.jellyfishing.client.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;